'use strict';
(() => {
  const data=window.SILICON_DATA,$=id=>document.getElementById(id);
  if(!data?.chips){$('app').textContent='The silicon database could not be loaded.';return;}
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safe=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
  const date=v=>{const d=new Date(v);return isNaN(d)?v:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).toUpperCase();};
  const launchYear=c=>{const launch=String(c.launch);if(/2027|2024|expected future/i.test(launch))return null;const explicit=launch.match(/\b(2025|2026)\b/);if(explicit)return Number(explicit[1]);return Number(String(c.date).slice(0,4))||null;};
  const chips=data.chips.filter(c=>[2025,2026].includes(launchYear(c)));
  const measurementMap=new Map([
    ['rtx-5090','NVIDIA GB202 (RTX 5090)'],['gorgonhalo','AMD Strix Halo SoC / iGPU die'],['spacemit-k1','SpacemiT K1 (RISC-V)'],['a19pro','Apple A19 Pro'],['panther','Intel Panther Lake-H'],['d9500','Dimensity 9500'],['exynos2600','Exynos 2600']
  ]);
  const measurements=new Map(chips.map(c=>[c.id,(data.dies||[]).find(d=>d.name===measurementMap.get(c.id))]).filter(x=>x[1]));
  const photos=new Map((window.SILICON_DIE_IMAGES||[]).filter(p=>p.chip_id&&chips.some(c=>c.id===p.chip_id)).map(p=>[p.chip_id,p]));
  const state={left:measurements.has('rtx-5090')?'rtx-5090':chips[0].id,right:photos.has('rx-9070-xt')?'rx-9070-xt':measurements.has('exynos2600')?'exynos2600':chips[1].id,scale:'true',target:'left',inspectorSide:'left',query:'',vendor:'All',status:'All'};
  const fields=[['process','Process'],['die','Physical silicon'],['cpu','CPU'],['gpu','GPU'],['ai','NPU / AI'],['memory','Memory / cache'],['launch','Launch'],['bench','Benchmarks']];
  const chip=id=>chips.find(c=>c.id===id)||chips[0];
  const status=c=>`<span class="status ${esc(c.status)}">${esc(c.status)}</span>`;
  const firstSource=c=>c.sources?.[0];
  function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,2600);}
  function picker(side,c){return `<div class="chip-picker"><select data-picker="${side}" aria-label="Choose ${side} comparison chip">${chips.map(x=>`<option value="${esc(x.id)}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select><div class="chip-meta"><span class="year">${launchYear(c)}</span>${status(c)}<span>${esc(c.vendor)} · ${esc(c.category)}</span></div></div>`;}
  function visual(c,maxArea){
    const d=measurements.get(c.id),photo=photos.get(c.id),source=d?.url||firstSource(c)?.url;
    if(!d){
      if(photo)return `<section class="specimen"><div class="die-wrap"><div class="die-visual photo unscaled" style="width:300px;height:300px"><img src="${esc(safe(photo.image))}" alt="Real die photograph of ${esc(c.name)}"></div></div><p class="image-note"><b>Licensed real photograph; displayed unscaled.</b> ${esc(photo.note||'')} ${esc(photo.author)} · <a href="${esc(safe(photo.license_url))}" target="_blank" rel="noopener">${esc(photo.license)}</a> · <a href="${esc(safe(photo.url))}" target="_blank" rel="noopener">Original image ↗</a></p></section>`;
      return `<section class="specimen"><div class="die-wrap"><div class="die-visual no-photo" style="width:210px;height:210px">${c.image?`<img src="${esc(c.image)}" alt="Illustrative diagram for ${esc(c.name)}">`:'<span>PHOTO NOT LICENSED</span>'}</div></div><p class="image-note">No reliable public die dimensions or reusable photograph yet.${source?` <a href="${esc(safe(source))}" target="_blank" rel="noopener">View current evidence ↗</a>`:''}</p></section>`;
    }
    const nums=d.dims.match(/[\d.]+/g).map(Number),factor=state.scale==='true'?Math.sqrt(d.area/maxArea):1;
    const base=330*factor,ratio=nums[0]/nums[1],w=ratio>=1?base:base*ratio,h=ratio>=1?base/ratio:base;
    const image=photo?.image||c.image,isPhoto=Boolean(photo);
    const note=isPhoto?`<b>${Number(d.area).toFixed(2)} mm² measured footprint with licensed real photograph.</b> ${esc(photo.note||'')} ${esc(photo.author)} · <a href="${esc(safe(photo.license_url))}" target="_blank" rel="noopener">${esc(photo.license)}</a> · <a href="${esc(safe(photo.url))}" target="_blank" rel="noopener">Original image ↗</a>`:`<b>${Number(d.area).toFixed(2)} mm² measured footprint.</b> A reusable photograph is not available, so this is an explicitly labelled diagram. <a href="${esc(safe(d.url))}" target="_blank" rel="noopener">View original die analysis ↗</a>`;
    return `<section class="specimen"><div class="die-wrap"><div class="die-visual ${isPhoto?'photo':image?'':'no-photo'}" style="width:${w}px;height:${h}px">${image?`<img src="${esc(isPhoto?safe(image):image)}" alt="${isPhoto?'Real die photograph':'Measured outline diagram'} for ${esc(c.name)}">`:'<span>PHOTO NOT LICENSED</span>'}<span class="dimension-x">${nums[0]} mm</span><span class="dimension-y">${nums[1]} mm</span></div></div><p class="image-note">${note}</p></section>`;
  }
  function evidenceCell(c,key){const e=c.field_evidence?.[key],warn=e&&e.status!=='Confirmed',photo=key==='die'&&photos.get(c.id),value=photo&&!measurements.has(c.id)?'Physical dimensions are not verified; the photograph is displayed unscaled.':c[key];return `<span class="evidence-dot ${warn?'warn':''}" title="${esc(e?.status||c.status)}"></span>${photo?'<b class="photo-fact">Licensed real photograph available.</b> ':''}${esc(value||'Not documented')}`;}
  function inspector(c){const d=measurements.get(c.id),photo=photos.get(c.id),sources=c.sources||[],imageStatus=photo?`Licensed real photograph · ${esc(photo.license)} · ${d?'scaled to verified dimensions':'unscaled'}`:d?'Measured diagram; source photo external':'No reusable die photo';return `<aside class="inspector"><small>SELECTED CHIP</small><h2>${esc(c.name)}</h2><div class="inspector-block"><h3>PHYSICAL MEASUREMENT</h3><dl><div class="fact"><dt>Die area</dt><dd>${d?`${Number(d.area).toFixed(2)} mm²`:'Not measured'}</dd></div><div class="fact"><dt>Dimensions</dt><dd>${esc(d?.dims||'Not available')}</dd></div><div class="fact"><dt>Process</dt><dd>${esc(c.process)}</dd></div><div class="fact"><dt>Image status</dt><dd>${imageStatus}</dd></div></dl></div><div class="inspector-block"><h3>EVIDENCE STATUS</h3><dl><div class="fact"><dt>Product</dt><dd>${status(c)}</dd></div><div class="fact"><dt>Record date</dt><dd>${esc(date(c.date))}</dd></div><div class="fact"><dt>Caveat</dt><dd>${esc(c.caveat)}</dd></div></dl></div><div class="inspector-block source-list"><h3>SOURCE TRAIL · ${sources.length}</h3>${sources.slice(0,5).map(s=>`<a href="${esc(safe(s.url))}" target="_blank" rel="noopener"><b>${esc(s.label)}</b><br><small>${esc(s.kind)} ↗</small></a>`).join('')}<button class="button" data-profile="${esc(c.id)}">Full dossier</button></div></aside>`;}
  function enhanceInspector(side=state.inspectorSide){const panel=document.querySelectorAll('.inspector')[0];if(!panel)return;panel.insertAdjacentHTML('afterbegin',`<div class="inspector-tabs" aria-label="Choose inspected chip"><button data-inspect="left" aria-pressed="${side==='left'}">Left</button><button data-inspect="right" aria-pressed="${side==='right'}">Right</button></div>`);panel.querySelectorAll('[data-inspect]').forEach(button=>button.onclick=()=>{state.inspectorSide=button.dataset.inspect;panel.outerHTML=inspector(chip(state[state.inspectorSide]));enhanceInspector();});}
  function compare(){const a=chip(state.left),b=chip(state.right),areas=[measurements.get(a.id)?.area||1,measurements.get(b.id)?.area||1],max=Math.max(...areas);$('app').innerHTML=`<div class="compare-shell"><div class="lab"><div class="compare-head">${picker('left',a)}<button class="swap" data-swap aria-label="Swap compared chips">⇄</button>${picker('right',b)}</div><div class="specimen-stage">${visual(a,max)}${visual(b,max)}</div><div class="lab-controls"><div class="segmented" aria-label="Die display scale"><button data-scale="true" aria-pressed="${state.scale==='true'}">True scale</button><button data-scale="fit" aria-pressed="${state.scale==='fit'}">Fit</button></div><button class="plain-button" data-copy>Copy comparison</button><span class="scale-note">True scale compares reported physical dimensions, not performance.</span></div><div class="spec-table">${fields.map(([key,label])=>`<div class="spec-row"><div class="spec-value">${evidenceCell(a,key)}</div><div class="label">${esc(label)}</div><div class="spec-value">${evidenceCell(b,key)}</div></div>`).join('')}</div><div class="filmstrip"><div class="filmstrip-head"><span class="section-kicker">2025–2026 CHIP INDEX · ${chips.length}</span><small>Replace: <button class="plain-button" data-target="left">Left</button> / <button class="plain-button" data-target="right">Right</button></small></div><div class="filmstrip-list">${chips.map(c=>`<button class="film-card" data-film="${esc(c.id)}" aria-pressed="${[state.left,state.right].includes(c.id)}"><b>${esc(c.name.replace(/ \([^)]*\)/g,''))}</b><small>${launchYear(c)} · ${esc(c.vendor)}</small><small>${measurements.has(c.id)?'Measured die':'Specs only'}</small></button>`).join('')}</div></div></div>${inspector(a)}</div>`;bindPickers();}
  function bindPickers(){document.querySelectorAll('[data-picker]').forEach(x=>x.onchange=e=>{state[e.target.dataset.picker]=e.target.value;state.target=e.target.dataset.picker;state.inspectorSide=e.target.dataset.picker;compare();});document.querySelectorAll('[data-film]').forEach(card=>{if(photos.has(card.dataset.film))card.lastElementChild.textContent='Licensed photo';});enhanceInspector();}
  function index(){const rows=chips.filter(c=>(state.vendor==='All'||c.vendor===state.vendor)&&(state.status==='All'||c.status===state.status)&&JSON.stringify(c).toLowerCase().includes(state.query.toLowerCase()));$('app').innerHTML=`<section class="page"><header class="page-header"><span class="section-kicker">CURATED LAUNCH WINDOW</span><h1>2025–2026<br>silicon index.</h1><p>Only chips launched or expected in this two-year window. Every row opens a source-backed dossier; measured dies can be sent directly into the comparison lab.</p></header><div class="toolbar"><input id="indexSearch" placeholder="Filter chips…" value="${esc(state.query)}"><select id="vendor"><option>All</option>${[...new Set(chips.map(c=>c.vendor))].sort().map(v=>`<option ${v===state.vendor?'selected':''}>${esc(v)}</option>`).join('')}</select><select id="status"><option>All</option>${['Confirmed','Engineering','Rumor','Expected'].map(v=>`<option ${v===state.status?'selected':''}>${v}</option>`).join('')}</select><span class="count">${rows.length} chips · ${rows.filter(c=>measurements.has(c.id)).length} measured dies</span></div><div class="chip-list">${rows.map(c=>`<article class="chip-row"><div><b>${esc(c.name)}</b><br><small>${esc(c.vendor)} · ${esc(c.category)}</small></div><span>${launchYear(c)}</span><span>${status(c)}</span><span class="optional">${esc(c.process)}</span><span class="optional">${measurements.has(c.id)?esc(measurements.get(c.id).dims):'Dimensions unavailable'}</span><button data-compare-chip="${esc(c.id)}">Compare</button></article>`).join('')}</div></section>`;$('indexSearch').oninput=e=>{state.query=e.target.value;index();};$('vendor').onchange=e=>{state.vendor=e.target.value;index();};$('status').onchange=e=>{state.status=e.target.value;index();};}
  function evidence(){const measured=[...measurements.keys()].length;$('app').innerHTML=`<section class="page"><header class="page-header"><span class="section-kicker">HOW TO READ THIS DATABASE</span><h1>Evidence before imagery.</h1><p>Silicon photography is valuable only when its identity, scale, provenance, and reuse rights are clear. This site never substitutes a marketing render for a real die shot.</p></header><div class="evidence-grid"><article class="evidence-card"><span class="section-kicker">REAL PHOTOGRAPH</span><h2>Displayed only with a reusable licence</h2><p>Licensed photographs retain their author, licence, and original source. We do not mirror copyrighted teardown or die-analysis imagery.</p></article><article class="evidence-card"><span class="section-kicker">MEASURED DIAGRAM</span><h2>${measured} current dies have dimensions</h2><p>These outlines preserve reported width, height, and area at a shared scale. They are diagrams, clearly labelled as such, with direct links to the physical-analysis source.</p></article><article class="evidence-card"><span class="section-kicker">SOURCE ONLY</span><h2>Absence is shown honestly</h2><p>When neither a reusable photo nor reliable dimensions exist, the interface says so. A chip launch does not confirm every physical claim.</p></article></div><div class="prose"><h2>Confirmed does not mean every field is confirmed</h2><p>Product status describes the product. Individual physical measurements, clocks, cache layouts, and benchmark claims can carry different evidence states. Conflicts remain visible and leaks never silently overwrite confirmed facts.</p><h2>Comparison guardrails</h2><p>Die area is not a performance score. Process-node labels are not directly comparable density metrics. TOPS require precision and sparsity context. Benchmarks require software, power, cooling, and sample context.</p><h2>Photography sources checked</h2><p>The reusable photo collection is drawn from Wikimedia Commons files with explicit licences. Current physical metadata links to Kurnal and other source records without copying their copyrighted imagery.</p><a class="button" href="data/live.json" download>Download public database</a></div></section>`;}
  function profile(id){const c=chip(id);$('profileContent').innerHTML=`<span class="section-kicker">${esc(c.vendor)} · ${launchYear(c)} · ${esc(c.category)}</span><h2 id="profileTitle" class="profile-title">${esc(c.name)}</h2>${status(c)}<p class="prose">${esc(c.headline)}</p><div class="profile-grid">${fields.map(([key,label])=>`<section><h3>${esc(label)}</h3><p>${esc(c[key]||'Not documented')}</p></section>`).join('')}</div><div class="inspector-block source-list"><h3>SOURCES</h3>${c.sources.map(s=>`<a href="${esc(safe(s.url))}" target="_blank" rel="noopener">${esc(s.label)} · ${esc(s.kind)} ↗</a>`).join('')}</div>`;$('profileDialog').showModal();}
  function navigate(){const view=(location.hash.slice(1).split('/')[0]||'compare');document.querySelectorAll('[data-view]').forEach(a=>a.setAttribute('aria-current',a.dataset.view===view?'page':'false'));if(view==='index')index();else if(view==='evidence')evidence();else compare();}
  function search(q){const rows=chips.filter(c=>JSON.stringify(c).toLowerCase().includes(q.toLowerCase())).slice(0,8),box=$('searchResults');box.hidden=!q;box.innerHTML=rows.map(c=>`<button data-profile="${esc(c.id)}"><span>${esc(c.name)}</span><small>${esc(c.vendor)} · ${launchYear(c)}</small></button>`).join('')||'<small>No matching chip in 2025–2026.</small>';}
  $('updated').textContent=date(data.meta.last_updated);
  $('globalSearchInput').oninput=e=>search(e.target.value.trim());
  $('globalSearch').onsubmit=e=>{e.preventDefault();state.query=$('globalSearchInput').value;location.hash='index';};
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-swap')){[state.left,state.right]=[state.right,state.left];compare();}if(b.dataset.scale){state.scale=b.dataset.scale;compare();}if(b.dataset.target)state.target=b.dataset.target;if(b.dataset.film){state[state.target]=b.dataset.film;state.target=state.target==='left'?'right':'left';compare();}if(b.dataset.compareChip){state[state.target]=b.dataset.compareChip;location.hash='compare';}if(b.dataset.profile)profile(b.dataset.profile);if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.hasAttribute('data-copy')){const url=location.href.split('#')[0]+`#compare/${encodeURIComponent(state.left)},${encodeURIComponent(state.right)}`;navigator.clipboard?.writeText(url).then(()=>toast('Comparison link copied.')).catch(()=>toast(url));}});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('globalSearchInput').focus();}if(e.key==='Escape')$('searchResults').hidden=true;});
  document.addEventListener('error',e=>{if(!e.target.matches?.('.die-visual.photo img'))return;const holder=e.target.parentElement,replacement=document.createElement('span');replacement.textContent='IMAGE SOURCE UNAVAILABLE';e.target.replaceWith(replacement);holder.classList.remove('photo');holder.classList.add('no-photo');toast('The external image source is temporarily unavailable.');},true);
  function syncComparisonHash(){const raw=location.hash.slice(1);if(raw.startsWith('compare/')){const ids=raw.slice(8).split(',').map(decodeURIComponent);if(chips.some(c=>c.id===ids[0]))state.left=ids[0];if(chips.some(c=>c.id===ids[1]))state.right=ids[1];}}
  window.addEventListener('hashchange',()=>{syncComparisonHash();navigate();});
  syncComparisonHash();navigate();
})();
